[package]
name = "smyth"
version = "0.1.0"

authors = ["David Cruz"]

[features]
default = ["syn"]

syn = ["syn"]
venial = ["venial"]

[dependencies]
syn = { version = "1", optional = true }
venial = { version = "0.5", optional = true }