[package]
name = "smyth"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1", features = ["full", "parsing", "extra-traits"], optional = true }
venial = { version = "0.5", optional = true }
thiserror = "1"

[dev-dependencies]
include_dir = "0.7.3"

[features]
default = ["syn"]